/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my;

import eventex.Ev;
import eventex.User;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Hasan Abdellatif
 */
public class evenui extends javax.swing.JPanel {
    User ui;
    Connection conn;
    ArrayList<Integer> crid ;
    ArrayList<Integer> attid ;
    /**
     * Creates new form evenui
     */
    public evenui() {
        initComponents();  
        checkdb();
    }
    public void checkdb()
    {
        ui = User_Int.us;
        int uid = ui.getUserID();
        conn = start.conn;
        cr.removeAllItems();
        cr.addItem("choose an event");
        att.removeAllItems();
        att.addItem("choose an event");
         try {
        Statement stat = conn.createStatement();
        //where Name = \""+ na + "\" AND Password = \""+ pa + "\""
        String sql = " Select Name,Id from Event where Owner ="+uid;
         ResultSet rs = stat.executeQuery(sql);
         //ArrayList<String> attnames = new ArrayList<String>();
         //ArrayList<String> crnames = new ArrayList<String>();
         attid = new ArrayList<Integer>();
         crid = new ArrayList<Integer>();
        while (rs.next())
        {
           cr.addItem(rs.getString("Name"));
           String id = rs.getString("Id");
           crid.add(Integer.parseInt(id));
        }
        String sql1 = " Select EventName,EventId from Attended where UserId ="+uid;
        ResultSet rs1 = stat.executeQuery(sql1);
       while (rs1.next())
        {
           att.addItem(rs1.getString("EventName"));
           String id = rs1.getString("EventId");
           attid.add(Integer.parseInt(id));
        }
        crl.setText("You have Created "+ crid.size()+" events");
        attl.setText("You might attend "+ attid.size()+" events");      
         }
         catch (Exception exc){
             JOptionPane.showMessageDialog(null, "Check Internet Connection!");
            exc.printStackTrace();   
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        crl = new javax.swing.JLabel();
        cr = new javax.swing.JComboBox<>();
        crb = new javax.swing.JButton();
        attb = new javax.swing.JButton();
        att = new javax.swing.JComboBox<>();
        attl = new javax.swing.JLabel();

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        crl.setForeground(new java.awt.Color(204, 204, 204));

        crb.setText("View");
        crb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crbActionPerformed(evt);
            }
        });

        attb.setText("View");
        attb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attbActionPerformed(evt);
            }
        });

        attl.setForeground(new java.awt.Color(204, 204, 204));

        jDesktopPane1.setLayer(crl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cr, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(crb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(attb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(att, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(attl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(attl, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                    .addComponent(att, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(attb))
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addComponent(cr, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(crb))))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(crl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(attl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(att, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attb))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crbActionPerformed
        // TODO add your handling code here
        int idev = cr.getSelectedIndex()-1;
        if(idev > -1)
        {
        idev = crid.get(idev);
        start.ui.showev(idev);
        }
    }//GEN-LAST:event_crbActionPerformed

    private void attbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attbActionPerformed
        // TODO add your handling code here:
        int idev = att.getSelectedIndex()-1;
        if(idev > -1)
        {
        idev = attid.get(idev);
        start.ui.showev(idev);
        }
    }//GEN-LAST:event_attbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> att;
    private javax.swing.JButton attb;
    private javax.swing.JLabel attl;
    private javax.swing.JComboBox<String> cr;
    private javax.swing.JButton crb;
    private javax.swing.JLabel crl;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
