/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventex;

import my.User_Int;

/**
 *
 * @author Hasan Abdellatif
 */
public class panel1 extends javax.swing.JPanel {
    User us;
    /**
     * Creates new form panel1
     */
    
    public panel1() {
          initComponents();
          us = User_Int.us;
        n.setText(n.getText()+us.getName());
         p.setText(p.getText()+us.getPassword());
          e.setText(e.getText()+us.getEmail());
           pr.setText(pr.getText()+us.getPreferences());
           
        
        
      
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan3 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        n = new javax.swing.JLabel();
        pr = new javax.swing.JLabel();
        e = new javax.swing.JLabel();
        p = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("My Account"));

        pan3.setBackground(new java.awt.Color(204, 204, 255));
        pan3.setForeground(new java.awt.Color(0, 153, 153));
        pan3.setEnabled(false);

        jDesktopPane1.setBackground(new java.awt.Color(0, 102, 102));

        n.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        n.setForeground(new java.awt.Color(204, 204, 204));
        n.setText("Name :  ");

        pr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pr.setForeground(new java.awt.Color(204, 204, 204));
        pr.setText("Perefernces:  ");

        e.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e.setForeground(new java.awt.Color(204, 204, 204));
        e.setText("Email :");

        p.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        p.setForeground(new java.awt.Color(204, 204, 204));
        p.setText("Password :  ");

        jDesktopPane1.setLayer(n, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(pr, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(e, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(p, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addComponent(pr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(e, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(n, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(pr, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pan3Layout = new javax.swing.GroupLayout(pan3);
        pan3.setLayout(pan3Layout);
        pan3Layout.setHorizontalGroup(
            pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        pan3Layout.setVerticalGroup(
            pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel e;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel n;
    private javax.swing.JLabel p;
    private javax.swing.JPanel pan3;
    private javax.swing.JLabel pr;
    // End of variables declaration//GEN-END:variables
}
